apiVersion: apps/v1
kind: Deployment
metadata:
  name: littb-snapshot-deploy
  labels:
    app: littb-snapshot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: littb-snapshot
  template:
    metadata:
      labels:
        app: littb-snapshot
    spec:
      containers:
      - name: littb-snapshot
        image: jroxendal/littb-snapshot
        ports:
        - containerPort: 8080

        # ´- /server
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            # httpHeaders:
            # - name: Custom-Header
            #   value: Awesome
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 7
---
kind: Service
apiVersion: v1
metadata:
  name: snapshot-svc
  labels:
    app: littb-snapshot
spec:
  selector:
    app: littb-snapshot
  ports:
  - protocol: TCP
    port: 7654
    targetPort: 8080
  type: LoadBalancer

